// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxi5wqn5Wi5NYKJxn_M_StJeF3hSsLqrA',
    appId: '1:507548863430:web:af373b41cbf60f89c1c0c7',
    messagingSenderId: '507548863430',
    projectId: 'smart-coach-e3b01',
    authDomain: 'smart-coach-e3b01.firebaseapp.com',
    storageBucket: 'smart-coach-e3b01.firebasestorage.app',
    measurementId: 'G-VCTLW4LH9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN-sb95vrPqtJDLcbCZqdDDqbV3rirU4Y',
    appId: '1:507548863430:android:dbee692fde40dd3fc1c0c7',
    messagingSenderId: '507548863430',
    projectId: 'smart-coach-e3b01',
    storageBucket: 'smart-coach-e3b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnESH3lujJVoG0iP9mKxZ285VLzJTXLYM',
    appId: '1:507548863430:ios:36b6343f673f68f4c1c0c7',
    messagingSenderId: '507548863430',
    projectId: 'smart-coach-e3b01',
    storageBucket: 'smart-coach-e3b01.firebasestorage.app',
    iosBundleId: 'com.example.smartCoachNew',
  );
}
